### ISSUE TITLE
Inconsistent scala 2.11.x dependency

### ISSUE THREAD

**Issue by maxm007** [dhpcs/scala-json-rpc#46]
Hi,

My project is constrained to scala 2.11.8, and the scala-json-rpc 1.5.0 release depends on scala 2.11.8, but its dependency play-json_2.11 , depends on scala 2.11.7.   

I can't find any scala-json-rpc release that has a consistent scala 2.11.8 dependency.   The team is adamant , we need this, so it looks like my only options is either to fork this project and create a release myself, or maybe have a release put on this github repo?

Thanks

Max

**Comment by dhpiggott** [comment]
Hi. I'd like to help, but I first need to make sure I understand the problem so I can be sure of what the solution should be.

Can you confirm what problem the inconsistency causes for you? Is it that you have strict dependency conflict resolution enabled and SBT fails when updating due to the patch version mismatch? Or does it not fail (standard dependency conflict resolution), but give an eviction warning? It would help if you could share a minimal example build definition that demonstrates the problem.

**Comment by maxm007** [comment]
Hi,

We have a rather large shared codebase with different teams working on it. 

Some time back issues were reported by some users using Maven, in scala.reflect.internal were it breaks between 2.11.6 and 2.11.8.   The problem arises when you have transitive dependencies on something relies on one of these packages.

It was decreed for stability reasons, to not have dependencies that have inconsistent scala versions, citing http://docs.scala-lang.org/overviews/core/binary-compatibility-of-scala-releases.html.

I'm sure there may be ways to work around this, but the reality on these large codebases is that it's not always practically easy to do or get past the gatekeepers.

This prevented me from adding a dependency to this scala-json-rpc, and I resorted to a private fork, where I basically have the latest version of your code, but running with scala 2.11.8 and play-json 2.6.0-M7 (which depends on scala 2.11.8).

Hope this helps and we can converge on an official release.

Thanks

**Comment by dhpiggott** [comment]
So if we were to do an official release of scala-json-rpc for this, would you want it to depend on Scala 2.11.8 and play-json 2.6.0-M7? Is there no non-milestone release of play-json that would suffice?

What do you think an appropriate version number would be for it? It's just that I don't think e.g. 2.0.1 or 2.1.0 would make sense and there aren't any immediately obvious alternatives that come to mind.

**Comment by maxm007** [comment]
Yeah, it's a bit unfortunate, but looks like for play-json, only milestone releases depend on 2.11.8.   Not sure what you do with that to be honest.  Does that leak into your versioning and your release also becomes a M release?  Should we ask for a official release of play-json with a non-milestone release? 

Maybe it's a big ask,.  I mean,  what we have works now, so if it's I suppose it's something for you to keep in mind in future releases.   Inconsistent scala dependencies can cause issues with binary compatibility.  Eventually we will upgrade scala release going through the whole process again

**Comment by dhpiggott** [comment]
Yeah, it's unfortunate. I don't think a scala-json-rpc release is the right way to fix it though.
